name: PAT Test

on:
  workflow_dispatch:


jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test PAT
        env:
            NOTES_TOKEN: ${{ secrets.NOTES_TOKEN }}
        run: |
            GITHUB_TOKEN=$NOTES_TOKEN; gh auth status; curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NOTES_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DuncanRoweWV/blahblah/pulls/1/merge \
            -d '{"commit_title":"Auto Merge","commit_message":"this bypasses branch protections"}'

            
