name: PAT Permission Test

on:
  workflow_dispatch:


jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test PAT
        env:
            NOTES_TOKEN: ${{ secrets.CONOR_PAT }}
        run: |
            GITHUB_TOKEN=$CONOR_PAT; gh auth status
