name: PAT Permission Test

on:
  workflow_dispatch:


jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test PAT
        env:
            NOTES_TOKEN: ${{ secrets.CONOR_PAT }}
        run: |
            sudo apt update
            sudo apt install gh jq -y
            gh auth login --with-token <<< $CONOR_PAT
            GITHUB_TOKEN=$CONOR_PAT
            gh auth status
