name: Check Security Labels

on:
  pull_request:
    types:
    - labeled

permissions:
  pull-requests: write
  issues: write

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if any security label is present
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredLabels = [
              "A: No Security Impact",
              "B: Security Review - light touch",
              "C: Threat Model",
              "D: Penetration Test"
            ];
          
            const labels = context.payload.pull_request.labels.map(label => label.name);
            
            // Define custom messages for each label
            const messages = {
              "A: No Security Impact": `Add the Security Approved Label`,
              
              "B: Security Review - light touch": `Please fill in this form: www.workvivo.com`,
              
              "C: Threat Model": `A message has been sent to the Workvivo security team.`,
            
              "D: Penetration Test": `A message has been sent to the Workvivo security team.`}
            
            for (const label of requiredLabels) {
              if (labels.includes(label)) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: messages[label]
                });
              }
            }
