name: Auto Label Issues

on:
  pull_request:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'security label' to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          labels: Security NOT Approved
