name: Auto Label Issues

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'security label' to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          labels: Security NOT Approved
      - name: Comment on PR 
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `
Please add a security label:
- [ ] A: No Security Impact
- [ ] B: Security Review - Light Touch
- [ ] C: Threat Model
- [ ] D: Penetration Test
Thanks!`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
