name: Test workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DuncanRoweWV/blahblah/pulls/1/merge \
          -d '{"commit_title":"Auto Merge","commit_message":"this bypasses branch protections"}'

          echo "Response: $RESPONSE"
             
